### PR TITLE
Add linter, remove internal/ remove src/

### PR DESCRIPTION
**Pull request by ldemailly**
Also, run
```
make
```
and/or set vscode go linter to `golangci-lint`

### CODE REVIEW

**Comment by rcornwell** [comment]
Unfortunately I can't accept this PR at this point. There are going to be about 40 packages in the internal directory when this project is finished. Right now the framework for this project is not even done. Right now all that exists is enough to test the port of channels and cpu objects.

**Comment by ldemailly** [comment]
it's your project :)

but

a) if you have 40 packages you're doing something wrong
b) have a look at the Makefile / linter setup

glad you at least removed src/ on your own, that's a start

**Comment by rcornwell** [comment]
I don't see a Makefile or anything for linter setup. I would take those, but moving stuff to the top level will be useful

**Comment by ldemailly** [comment]
My bad I forgot to git add the 2 files (!)

https://github.com/rcornwell/S370/pull/2

**Pull request closed without merging**
